import { DM_Sans } from "next/font/google"
import "./globals.css"
import Footer from "@/components/layout/Footer";
import Nav from "@/components/layout/Nav";

const geistSans = DM_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--geist-sans'
})

export const metadata = {
  title: "Juntii | Empieza a ahorrar y pedir como nunca antes",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.className}`}>
        <Nav/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
